2 task
veiuper/todolist pull request #7
Opened 2022-05-06 08:39 UTC by veiuper

2022-05-06 12:09 UTC, Rinat-G requested changes
Дополнительно предлагаю сделать:
1) переделать инжекции в поля на инжкецию в конструктор для контроллера и сервиса
2) выводимый список задач сортировать по id и статусу выполнения чтобы при нажатии на "выполнить" задачи хаотично не скакали по списку.

2022-05-06 12:09 UTC, Rinat-G commented on src/main/java/com/veiuper/todolist/service/TaskService.java
> +            throw new Exception();
нужно бросить осмысленное исключение. Лучше рантайм, чтобы его потом везде не пихать в throws )

2022-05-06 12:09 UTC, Rinat-G commented on src/main/java/com/veiuper/todolist/model/Task.java
> +    public void setStatus(Boolean executed) {
по сути у нас здесь сеттер для поля executed. мжт его тогда так и назвать "setExecuted" ?

2022-05-07 06:51 UTC, veiuper commented
> Дополнительно предлагаю сделать:
> 
> 1. переделать инжекции в поля на инжкецию в конструктор для контроллера и сервиса
> 2. выводимый список задач сортировать по id и статусу выполнения чтобы при нажатии на "выполнить" задачи хаотично не скакали по списку.

Реализовано в:
https://github.com/veiuper/todolist/pull/7/commits/040e3ceb3875006a73b36fbc5531466bd15f6a32

2022-05-08 07:38 UTC, veiuper commented on src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=create
Установил update для стадии активной разработки.

2022-05-08 07:38 UTC, veiuper commented on src/main/java/com/veiuper/todolist/controller/TaskController.java
> +    @RequestMapping("/reversTaskStatus/{id}")
Изменил.

2022-05-08 07:39 UTC, veiuper commented
> Дополнительно предлагаю сделать:
> 
> 1. переделать инжекции в поля на инжкецию в конструктор для контроллера и сервиса
> 2. выводимый список задач сортировать по id и статусу выполнения чтобы при нажатии на "выполнить" задачи хаотично не скакали по списку.

1. Переделал.
2. Сортировка по статусу потом по id.

2022-05-08 07:45 UTC, veiuper commented on src/main/java/com/veiuper/todolist/model/Task.java
> +    public void setStatus(Boolean executed) {
Изменил.

2022-05-08 07:47 UTC, veiuper commented on src/main/java/com/veiuper/todolist/service/TaskService.java
> +            throw new Exception();
Изменил на BusinessException с осмысленным текстом.

2022-05-08 13:09 UTC, veiuper commented
Кроме валидации все сделано.

2022-06-07 12:08 UTC, merged